#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_FILE="${ROOT_DIR}/docs/src/reference/cli.md"

export CARGO_TERM_COLOR=never

run_help() {
  local args=("$@")
  if command -v branchbox >/dev/null 2>&1; then
    branchbox "${args[@]}" --help
  else
    cargo run --quiet -p branchbox-cli -- "${args[@]}" --help
  fi
}

write_header() {
  cat <<'EOF'
# CLI Reference

The sections below are generated by `docs/scripts/render-cli-reference.sh`. Do not edit manually—run the script instead after changing CLI arguments.
EOF
}

append_section() {
  local title="$1"
  shift
  local args=("$@")
  {
    echo
    echo "## ${title}"
    echo
    echo '```text'
    if [ "${#args[@]}" -eq 0 ]; then
      run_help
    else
      run_help "${args[@]}"
    fi
    echo '```'
  } >>"${OUT_FILE}"
}

main() {
  : >"${OUT_FILE}"
  write_header >"${OUT_FILE}"

  append_section "branchbox"
  append_section "branchbox init" init
  append_section "branchbox detect" detect
  append_section "branchbox name" name
  append_section "branchbox name generate" name generate "SAMPLE TITLE"
  append_section "branchbox name validate" name validate sample-feature
  append_section "branchbox feature" feature
  append_section "branchbox feature start" feature start
  append_section "branchbox feature list" feature list
  append_section "branchbox feature teardown" feature teardown sample-feature
}

main "$@"
